-
  method: r301
  from: !ruby/regexp '/(.*)/'
  to:   'https://www.locationmachine.io$1'
  options:
    host:   'locationmachine.io'

-
  method: r301
  from: !ruby/regexp '/(.*)/'
  to:   'https://www.locationmachine.io$1'
  options:
    host:   'www.locationmachine.io'
    scheme: 'http'

